
import Header from '@/components/Header/Header'
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import './globals.css'
import AuthProvider from '@/components/AuthProvider/AuthProvider';
 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AuthProvider>
          <ToastContainer />
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
